query ListEverything @auth(level: PUBLIC) {
  movies {
    id
    originalLanguage
    availableLanguages
  }
}

query FilterMovies($originalLanguage: Language) @auth(level: PUBLIC) {
  movies(where: { originalLanguage: { eq: $originalLanguage } }) {
    id
    originalLanguage
    availableLanguages
  }
}
